title: Unifi Protect Exporter Documentation
description: High-performance Prometheus exporter for Unifi Protect API metrics with comprehensive monitoring capabilities and OpenTelemetry support

# Global meta tags for all pages
tags:
  - prometheus
  - monitoring
  - unifi-protect
  - network-monitoring
  - observability

# Social media defaults
image: assets/og-image.png
twitter:
  creator: "@rknightion"
  site: "@rknightion"

# SEO defaults
robots: index,follow
language: en
canonical_base: https://rknightion.github.io/unifi-protect-exporter/
